# Generated by Django 5.1.2 on 2024-12-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_book_isbn_book_available_copies_transactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='links',
            field=models.URLField(null=True),
        ),
    ]
