# Generated by Django 5.1.2 on 2024-12-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0005_alter_book_available_copies_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='check_out_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
