# Generated by Django 5.1.2 on 2024-12-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0006_alter_checkout_check_out_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
