# Generated by Django 5.1.2 on 2025-01-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0008_alter_checkout_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
