# Generated by Django 5.1.2 on 2025-01-03 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0009_book_is_checked_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_checked_out',
        ),
    ]
