# Generated by Django 5.1.2 on 2025-01-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0010_remove_book_is_checked_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField( unique=True,default=0),
        ),
    ]
