# Generated by Django 5.1.2 on 2025-01-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0014_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='return_date',
            field=models.DateTimeField(blank=True, default=False, null=True),
        ),
    ]
