# Generated by Django 5.1.2 on 2025-01-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0015_alter_book_isbn_alter_checkout_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
